[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    'solmate/auth/=lib/solmate/src/auth',
]

[fuzz]
runs = 100_000_000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
